### ISSUE TITLE
Grub settings update

### ISSUE THREAD

**Issue by mfortin** [ansible-lockdown/AMAZON2-CIS#31]
**Feature Request or Enhancement**
 - Feature []
 - Enhancement [X]

**Summary of Request**
Sections 4.1.1.3 and 4.1.2.4 updates settings in /etc/default/grub, however Amazon Linux 2 default file content has a different line than exected.

**Describe alternatives you've considered**
Here is the default content from `/etc/default/grub/`:
```
GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0"
GRUB_TIMEOUT=0
GRUB_DISABLE_RECOVERY="true"
GRUB_TERMINAL="ec2-console"
GRUB_X86_USE_32BIT="true"
```
Both sections above attempts to read content from line starting with `GRUB_CMDLINE_LINUX=` which doesn't exist.
Ending up in `/etc/default/grub` to be updated to:
```
GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0"
GRUB_TIMEOUT=0
GRUB_DISABLE_RECOVERY="true"
GRUB_TERMINAL="ec2-console"
GRUB_X86_USE_32BIT="true"
GRUB_CMDLINE_LINUX=" audit=1 audit_backlog_limit=8192"
```
**Suggested Code**
Updating code to the below would update the GRUB_CMDLINE_LINUX_DEFAULT line in file.
```
- name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  block:
      - name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Get Grub CMDLINE Settings"
        shell: grep -c -E '^GRUB_CMDLINE_LINUX(_DEFAULT)?=' /etc/default/grub
        changed_when: false
        failed_when: false
        register: amazon2cis_4_1_1_3_grub_cmdline_linux

      - name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Set if Grub CMDLINE exists"
        lineinfile:
            path: /etc/default/grub
            regexp: '^(GRUB_CMDLINE_LINUX(?:_DEFAULT)?)="(.*)( audit=\d)?(.*)"'
            line: '\1="\2 audit=1\3"'
            backrefs: true
        notify: grub2cfg
        when: "'1' in amazon2cis_4_1_1_3_grub_cmdline_linux.stdout"

      - name: "4.1.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Set if Grub CMDLINE does not exist"
        lineinfile:
            path: /etc/default/grub
            line: 'GRUB_CMDLINE_LINUX="audit=1"'
        notify: grub2cfg
        when: "'0' in amazon2cis_4_1_1_3_grub_cmdline_linux.stdout"
  when:
      - amazon2cis_rule_4_1_1_3
  tags:
      - level2
      - automated
      - patch
      - rule_4.1.1.3
      - auditd
```
and
```
- name: "4.1.2.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  block:
      - name: "4.1.2.4 | AUDIT | Ensure audit_backlog_limit is sufficient | Grep GRUB_CMDLINE_LINUX parameter"
        shell: grep -c -E 'GRUB_CMDLINE_LINUX(_DEFAULT)?=' /etc/default/grub
        changed_when: false
        failed_when: false
        register: amazon2cis_4_1_2_4_grub_cmdline_linux_settings

      - name: "4.1.2.4 | PATCH | Ensure audit_backlog_limit is sufficient | Set audit_backlog_limit if GRUB_CMDLINE_LINUX exists"
        lineinfile:
            path: /etc/default/grub
            regexp: '^(GRUB_CMDLINE_LINUX(?:_DEFAULT)?)="(.*)( audit_backlog_limit={{ amazon2cis_audit_backlog_limit }})?(.*)"'
            line: '\1="\2 audit_backlog_limit={{ amazon2cis_audit_backlog_limit }}\3"'
            backrefs: true
        notify: grub2cfg
        when: "'1' in amazon2cis_4_1_2_4_grub_cmdline_linux_settings.stdout"

      - name: "4.1.2.4 | PATCH | Ensure audit_backlog_limit is sufficient | Set audit_backlog_limit if GRUB_CMDLINE_LINUX does not exists"
        lineinfile:
            path: /etc/default/grub
            replace: 'GRUB_CMDLINE_LINUX="audit_backlog_limit={{ amazon2cis_audit_backlog_limit }}"'
        notify: grub2cfg
        when: "'0' in amazon2cis_4_1_2_4_grub_cmdline_linux_settings.stdout"
  when:
      - amazon2cis_rule_4_1_2_4
  tags:
      - level2
      - automated
      - patch
      - rule_4.1.2.4
      - grub
```
